openapi: 3.0.0
info:
  title: Action Device API
  description: An API for managing device action. For each device actions status store
    inside server database. Set Action for device from GUI, device is responsible
    to reset it after performing action.
  contact:
    name: Edgeway
    email: devops.vep@smardtv.com
  version: 1.0.0

servers:
  - url: https://ewm-preprod.edgeway.io
    description: Dev Server
  
  - url: https://ewm-preprod-mt.edgeway.io
    description: Prod Server

paths:
  /api/device/v1/action/{deviceId}:
    put:
      summary: Update the device action from device.
      description: Update the device action from device.
      security:
      - bearerAuth: []
      parameters:
      - name: deviceId
        in: path
        description: device id of device under question
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        200:
          description: device action is updated.
        400:
          description: Missing/malformed request parameters or body. See error for
            details.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        401:
          description: The user is not authenticated.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: Internal error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      summary: Create default the device action.
      description: Create default the device action.
      security:
      - bearerAuth: []
      parameters:
      - name: deviceId
        in: path
        description: device id of device under question
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        200:
          description: device action is updated.
        400:
          description: Missing/malformed request parameters or body. See error for
            details.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: Internal error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    get:
      summary: Get device action.
      description: Get device action.
      security:
      - bearerAuth: []
      parameters:
      - name: deviceId
        in: path
        description: device id of device under question
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        200:
          description: device action is updated.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Device_Action'
        404:
          description: status not found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: Internal error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    Error:
      type: object
      properties:
        error:
          type: string
          description: Description of the error.
        request_id:
          type: string
          description: Request ID (same as in X-MEN-RequestID header).
      description: Error descriptor.
      example:
        error: 'Error string'
        request_id: f7881e82-0492-49fb-b459-795654e7188a

    Device_Params:
      type: object
      description: device param status and details
      properties:
        status:
          type: integer
        details:
          type: string

    Device_Action:
      type: object
      properties:
        actions:
          $ref: '#/components/schemas/Device_Params'
        env_vars:
          $ref: '#/components/schemas/Device_Params'
        enablers:
          $ref: '#/components/schemas/Device_Params'

  responses:
    UnauthorizedError:
      description: Access token in missing or invalid
