openapi: 3.0.0
info:
  title: Device action API
  description: An API for managing device action. For each device actions status store
    inside server database. Set Action for device from GUI, device is responsible
    to reset it after performing action.
  contact:
    name: Alap vyas
    url: smardtv.com
    email: alap.vyas@smardtv.com
  version: 1.0.0
servers:
- url: https://smarthing-cloud-dev.com
  description: Dev Server
- url: https://smarthing-cloud.com
  description: Prod Server
paths:
  /api/management/v1/action/{deviceId}:
    get:
      summary: get the device action.
      parameters:
      - name: deviceId
        in: path
        description: device id of device under question
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        200:
          description: device action returned.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/action'
        400:
          description: Missing/malformed request parameters or body. See error for
            details.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        401:
          description: The user is not authenticated.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: Internal error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    put:
      summary: update the device action.
      parameters:
      - name: deviceId
        in: path
        description: device id of device under question
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        200:
          description: device action is updated.
        400:
          description: Missing/malformed request parameters or body. See error for
            details.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        401:
          description: The user is not authenticated.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: Internal error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      description: Creates new device action.
      parameters:
      - name: deviceId
        in: path
        description: Device Id for which local configuration is added
        required: true
        style: simple
        explode: false
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/action'
        required: true
      responses:
        200:
          description: Successfull addition of the local configuration
        400:
          description: Missing/malformed request parameters or body. See error for
            details.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        401:
          description: The device is not authenticated.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: Internal error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    delete:
      summary: delete the action of a device.
      parameters:
      - name: deviceId
        in: path
        description: device id of device under question
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        200:
          description: device action is deleted.
        400:
          description: Missing/malformed request parameters or body. See error for
            details.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        401:
          description: The user is not authenticated.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: Internal error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /api/management/v1/action/list:
    get:
      summary: Get the list of device actions.
      parameters:
      - name: page
        in: query
        description: Starting page, default 1.
        required: false
        style: form
        explode: true
        schema:
          type: integer
      - name: per_page
        in: query
        description: Number of results per page, default 20.
        required: false
        style: form
        explode: true
        schema:
          type: integer
      responses:
        200:
          description: A list of local configurations.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ArrayOfActions'
        400:
          description: Missing/malformed request parameters or body. See error for
            details.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        401:
          description: The user is not authenticated.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: Internal error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Error:
      type: object
      properties:
        error:
          type: string
          description: Description of the error.
        request_id:
          type: string
          description: Request ID (same as in X-MEN-RequestID header).
      description: Error descriptor.
      example:
        error: 'failed to decode device group data: JSON payload is empty'
        request_id: f7881e82-0492-49fb-b459-795654e7188a
    action:
      type: object
      properties:
        config_details:
          type: string
          description: JSON string with device action details
        device_id:
          type: string
          description: device id for which action has triggerd
        id:
          type: string
          description: db assigned id
        created_ts:
          type: string
          description: Created timestamp
          format: datetime
        updated_ts:
          type: string
          description: Updated timestamp
          format: datetime
      description: device action model
      example:
        actions: '{"Reboot":"true", "reset":"true", "uart":"true","open_port":"80"}'
        created_ts: 2019-04-16T06:44:16.386Z
        device_id: "1"
        env_vars: '{"config_poll_interval":"2", "flavor_poll_interval":"2","actions_poll_interval":"2"}'
        id: 5cb579c066b19200019d546f
        updated_ts: 2019-04-16T06:44:16.386Z
    ArrayOfActions:
      type: array
      description: array of local configurations
      items:
        $ref: '#/components/schemas/action'
  responses:
    UnauthorizedError:
      description: Access token in missing or invalid
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
