openapi: 3.0.1
info:
  version: '1.0.0'
  title: 'Device inventory Device API'
  description: 'An API for uploading device attributes. Intended for use by devices.
                Devices can upload vendor-specific attributes (software/hardware info, 
                health checks, metrics, etc.) of various data types to the backend.'
  contact:
    name: Edgeway
    email: devops.vep@smardtv.com

servers:
  - url: https://ewm-preprod.edgeway.io
    description: Dev Server
  
  - url: https://ewm-preprod-mt.edgeway.io
    description: Prod Server

paths:
  /api/devices/v1/inventory/device/attributes:
    patch:
      summary: Upload a set of attributes for a device
      description: |
        Saves the provided attribute set for the authenticated device.
        The device ID is retrieved from the authorization header.

        This method has upsert semantics:
        * the values of existing attributes are overwritten
        * attributes uploaded for the first time are automatically created
      security:
      - bearerAuth: []
      requestBody:
        description: A list of attribute descriptors.
        content:
          application/json:
            schema:
              title: ListOfAttributes
              type: array
              example:
                application/json:
                - name: ip_addr
                  value: 1.2.3.4
                  description: IP address
                - name: mac_addr
                  value: 00.01:02:03:04:05
                  description: MAC address
                - name: ports
                  value:
                  - "8080"
                  - "8081"
                  description: Open ports
              items:
                $ref: '#/components/schemas/Attribute'
        required: true
      responses:
        200:
          description: Attributes were uploaded successfully.
          content: {}
        400:
          description: Missing/malformed request parameters or body. See error for
            details.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        401:
          description: The device is not authenticated.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: Internal server error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      x-codegen-request-body-name: attributes

components:

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    Attribute:
      required:
      - name
      - value
      type: object
      properties:
        name:
          type: string
          description: |
            A human readable, unique attribute ID, e.g. 'device_type', 'ip_addr', 'cpu_load', etc.
        description:
          type: string
          description: Attribute description.
        value:
          type: string
          description: |
            The current value of the attribute.

            Attribute type is implicit, inferred from the JSON type.

            Supported types: number, string, array of numbers, array of strings. Mixed arrays are not allowed.
      description: Attribute descriptor.
      example:
        application/json:
          name: cpu_load
          description: The current CPU load.
          value: 42
    Error:
      type: object
      properties:
        error:
          type: string
          description: Description of the error.
        request_id:
          type: string
          description: Request ID (same as in X-MEN-RequestID header).
      description: Error descriptor.
      example:
        application/json:
          error: 'Error string'
          request_id: f7881e82-0492-49fb-b459-795654e7188a
