openapi: 3.0.1
info:
  version: '1.0.0'
  title: 'Device inventory Internal API'
  description: 'An API for device attribute management and device grouping.
                Not exposed via the API Gateway - intended for internal use only.'
  contact:
    name: Edgeway
    email: devops.vep@smardtv.com

servers:
  - url: https://ewm-preprod.edgeway.io
    description: Dev Server
  
  - url: https://ewm-preprod-mt.edgeway.io
    description: Prod Server

paths:
  /api/internal/v1/inventory/tenants:
    post:
      summary: Create tenant
      description: |
        Create a tenant with provided configuration.
      security:
      - bearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TenantNew'
        required: true
      responses:
        201:
          description: The tenant was created successfully.
          content: {}
        400:
          description: Missing or malformed request parameters.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: Unexpected error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      x-codegen-request-body-name: tenant
  /api/internal/v1/inventory/devices:
    post:
      summary: Create a device resource with the supplied set of attributes
      description: Create a device resource with the supplied set of attributes
      security:
      - bearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DeviceNew'
        required: true
      responses:
        201:
          description: The device was successfully created.
          headers:
            Location:
              description: URI for the newly created 'Device' resource.
              schema:
                type: string
          content: {}
        400:
          description: Malformed request body. See error for details.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: Internal server error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      x-codegen-request-body-name: device

components:

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    Error:
      type: object
      properties:
        error:
          type: string
          description: Description of the error.
        request_id:
          type: string
          description: Request ID (same as in X-MEN-RequestID header).
      description: Error descriptor.
      example:
        application/json:
          error: 'Error string'
          request_id: f7881e82-0492-49fb-b459-795654e7188a
    TenantNew:
      type: object
      properties:
        tenant_id:
          type: string
          description: ID of given tenant.
      description: Tenant configuration.
      example:
        application/json:
          tenant_id: "1234"
    DeviceNew:
      required:
      - id
      type: object
      properties:
        id:
          type: string
          description: Mender-assigned unique ID.
        updated_ts:
          type: string
          description: Timestamp of the most recent attribute update.
        attributes:
          type: array
          description: A list of attribute descriptors.
          items:
            $ref: '#/components/schemas/Attribute'
      example:
        application/json:
          id: 291ae0e5956c69c2267489213df4459d19ed48a806603def19d417d004a4b67e
          attributes:
          - name: ip_addr
            value: 1.2.3.4
            description: IP address
          - name: mac_addr
            value: 00.01:02:03:04:05
            description: MAC address
          - name: ports
            value:
            - "8080"
            - "8081"
            description: Open ports
    Attribute:
      required:
      - name
      - value
      type: object
      properties:
        name:
          type: string
          description: |
            A human readable, unique attribute ID, e.g. 'device_type', 'ip_addr', 'cpu_load', etc.
        description:
          type: string
          description: Attribute description.
        value:
          type: string
          description: |
            The current value of the attribute.

            Attribute type is implicit, inferred from the JSON type.

            Supported types: number, string, array of numbers, array of strings. Mixed arrays are not allowed.
      description: Attribute descriptor.
      example:
        application/json:
          name: cpu_load
          description: The current CPU load.
          value: 42
