openapi: '3.0.0'
info:
  version: '1.0.0'
  title: Useradm Managenet API
  description: |
    An API for management.

servers:
  - url: '{protocol}://trial.edgeway.io/{basePath}'
    variables:
      protocol:
        enum: [http, https]
        default: https
      basePath: 
        enum: [/api/management/v1/useradm/auth]
        default: /api/management/v1/useradm/auth

paths:
  /forgotpwd:
    description: Send the URL link to reset the password on provided Email
    post:
      summary: form a reset link and send email
      parameters:
        - name: email
          in: query
          description: email id
          required: true
          schema:
            type: string
      responses:
        200:
          description: Success to send reset link to provided email.
        400:
          description: Missing/malformed request params.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: Unexpected error

  /verify:
    description: Verify link sent on mail of user
    get:
      summary: Authenticate the mail User
      description: Authenticate the URL
      parameters:
        - name: email
          in: query
          description: email id
          required: true
          schema:
            type: string
        - name: token
          in: query
          description: JWT token hash
          required: true
          schema:
            type: string
      responses:
        303:
          description: redirected to password reset page
        400:
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        404:
          description: not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /reset:
    description: reset the password of user
    post:
      summary: reset the user password
      requestBody:
        description: password reset payload
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/passwordreset'
      responses:
        204:
          description: Succes to update the password
        400:
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        404:
          description: not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: Unexpected error

  /users/{id}/role:
    description: get the role by id
    get:
      summary: get the role (admin/viewer) by user ID
      parameters:
        - name: id
          in: path
          description: DB id
          required: true
          schema:
            type: string
      responses:
        200:
          description: success to get role
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Role'
        400:
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        404:
          description: not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /oauth2/auth0:
    get:
      description: auth0 verification
      responses:
        303:
          description: redirected to authenticate code
        401:
          description: Authorisation failed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        404:
          description: not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /oauth2/auth0/login:
    get:
      description: auth 2 login
      responses:
        303:
          description: On success redirected to verify email
                       On failure redirected to sign-up page
        400:
          description: Bad parameters
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        401:
          description: Authorisation failed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        404:
          description: not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'


components:
  responses:
    UnauthorizedError:
      description: Access token in missing or invalid

  schemas:
    Error:
      description: Error descriptor
      type: object
      properties:
        error:
          description: Description of the error
          type: string
    passwordreset:
      description: reset payload
      type: object
      properties:
        email:
          type: string
        password:
          type: string
        captchacode:
          type: string
    Role:
      description: role of user id
      type: object
      properties:
        role:
          type: string
