openapi: 3.0.0
info:
  version: '1.0.0'
  title: 'Useradm API'
  description: 'APIs for Managing useradm'
  contact:
    name: Dhruvit Patel
    url: smardtv.com

servers:
  - url: https://smarthing-cloud-dev.com
    description: Dev Server

  - url: http://smarthing-cloud.com
    description: Prod Server


paths:
  /api/internal/v1/useradm/tenants/{tenant_id}/users:
    get:
      description: get tenant users
      parameters:
        - name: tenant_id
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: All configuration
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ArrayOfUser'
        404:
          description: not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: Internal error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  responses:
    UnauthorizedError:
      description: Access token in missing or invalid

  schemas:

    Error:
      description: Error descriptor.
      type: object
      properties:
        error:
          description: Description of the error.
          type: string
        request_id:
          description: Request ID (same as in X-MEN-RequestID header).
          type: string
      example:
        error: "failed to decode device group data: JSON payload is empty"
        request_id: "f7881e82-0492-49fb-b459-795654e7188a"


    ArrayOfUser:
      description: array of users
      type: array
      items:
        $ref: '#/components/schemas/User'

    User:
      description: device configuration map
      type: object
      properties:
        id:
          description: DB assigned ID
          type: string
        Email:
          description: email id
          type: string
        password:
          description: password
          type: string
        role:
          description: role of user
          type: string
        auth0:
          description: authentication
          type: string
        created_ts:
          type: string
          format: datetime
          description: Created timestamp
        updated_ts:
          type: string
          format: datetime
          description: Updated timestamp
