openapi: '3.0.0'
info:
  version: '1.0.0'
  title: 'Infra-manager Device API'
  description: 'An Device api to get the domainname of tenant'
  contact:
    name: Edgeway
    email: devops.vep@smardtv.com

servers:
  - url: https://ewm-preprod.edgeway.io
    description: Dev Server

  - url: https://ewm-preprod-mt.edgeway.io
    description: Prod Server

paths:
  /api/edgeway/ewv/v1/infra_manager/infrastructure:
    get:
      description: Get domain name from insfrastructure for particular tenant
      summary: Get domain name from insfrastructure for particular tenant
      security:
        - bearerAuth: []
      responses:
          200:
            description: infrastructurs object
                          This will be returned on if infrastructure is present.
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/InfrastructureUrl'
          400:
            description: Bad request
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Error'
          401:
            description: Authorization failed
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Error'
          500:
            description: Unexpected error
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Error'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Error:
      type: object
      properties:
        error:
          type: string
          description: Description of the error.
        request_id:
          type: string
          description: Request ID (same as in X-MEN-RequestID header).
      description: Error descriptor.
      example:
        error: 'Error string'
        request_id: f7881e82-0492-49fb-b459-795654e7188a
    InfrastructureUrl:
      description: Infrastructure domain name
      type: object
      properties:
        domain_name:
          type: string
        public_ip:
          type: string
      example: {"domain_name":"ewm-prep.edgeway.io", "public_ip":"12.22.02.172"}
