openapi: 3.0.0
info:
  version: '1.0.0'
  title: 'Configurations Device API'
  description: 'APIs for requesting configurations and flavour for a Device.'
  contact:
    name: Edgeway
    email: devops.vep@smardtv.com

servers:
  - url: https://ewm-preprod.edgeway.io
    description: Dev Server
  
  - url: https://ewm-preprod-mt.edgeway.io
    description: Prod Server

  
paths: 
  /api/devices/v1/configurations/config_requests/{deviceId}:
    get:
      summary: Device API to get the configuration and flavor for the deviceId
      security:
      - bearerAuth: []
      parameters:
        - name: deviceId
          required: true
          in: path
          description: Device Id of chosen device.
          schema:
            type: string
      responses:
        200:
          description: configuration map
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConfigMap'
        400:
          description: Missing/malformed request parameters or body. See error for details.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        401:
          description: The device is not authenticated.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: Internal error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    Error:
      description: Error descriptor.
      type: object
      properties:
        error:
          description: Description of the error.
          type: string
        request_id:
          description: Request ID (same as in X-MEN-RequestID header).
          type: string
      example:
        error: "Error string"
        request_id: "f7881e82-0492-49fb-b459-795654e7188a"

    ConfigMap:
      description: Device configurations map
      type: object
      properties:
        configuration:
          type: object
          properties:
            config_details:
              description: JSON string of configurations
              type: string
            name:
              description: name of the configuration
              type: string
            type:
              description: type of the configuration
        device_id:
          description: device id under question
          type: string
        flavor:
          description: flavor mapped to device
          type: object
          properties:
            container:
              description: JSON string of container details
              type: string
            name:
              description: name of configuration flavor
              type: string
            type:
              description: type of the cofiguration flavor
              type: string
        unique_dev_parameters:
          description: Unique device parameters associated ex. comments
          type: string
      example:
        configuration: 
           config_details: "{ \"protection_type\" : \"LinkProt\", \"key_rotation_period\" : \"15\", \"key_predelivery_win\" : \"1\", \"cam_net_if\" : \"eth0\", \"cam_onvif_port\" : \"92\", \"cam_rtsp_port\" : \"990\", \"cam_addr\" : \"9900\", \"cam_port\" : \"121\" }"
           name: "VSASS_Test2"
           type: "VSAAS"
          
        device_id: "5ca5c7352d740400018a214e"
        flavor: 
          container: "{ \"protection_type\" : \"LinkProt\", \"key_rotation_period\" : \"15\", \"key_predelivery_win\" : \"1\", \"cam_net_if\" : \"eth0\", \"cam_onvif_port\" : \"92\", \"cam_rtsp_port\" : \"990\", \"cam_addr\" : \"9900\", \"cam_port\" : \"121\" }"
          name: "VSAAS"
          type: "VSAAS"
        unique_devparams: "testUniqueParams"
