openapi: 3.0.0
info:
  version: '1.0.0'
  title: 'Local Confiuguration Device API'
  description: 'API for managing  local configurations.
                For device to store a bulk of data inside server database.
                Device is responsible of creating/updating/deleting content of data.
                Data is unique by device'
  contact:
    name: Edgeway
    email: devops.vep@smardtv.com

servers:
  - url: https://ewm-preprod.edgeway.io
    description: Dev Server
  
  - url: https://ewm-preprod-mt.edgeway.io
    description: Prod Server

paths: 
  /api/devices/v1/localconf/lconf_requests/{deviceId}:
    patch: 
        summary: Add the local configuration details for VSAAS flavor
        description: Add the local configuration details for VSAAS flavor
        security:
          - bearerAuth: []
        parameters:
         - name : deviceId
           required: true
           in: path
           description: Device Id for which local configuration is added
           schema:
             type: string
        
        requestBody:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Lconf'

        responses:
          200:
            description: Successfull addition of the local configuration
          
          400:
            description: Missing/malformed request parameters or body. See error for details.
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Error'

          401:
            description: The device is not authenticated.
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Error'

          500:
            description: Internal error.
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Error'

    post:
      summary: Add local configuration
      description: Add local configuration
      security:
      - bearerAuth: []
      parameters:
        - in: path
          name: deviceId
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LocalConf'
      responses:
          200:
            description: Successfull addition of the local configuration

          400:
            description: Missing/malformed request parameters or body. See error for details.
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Error'

          401:
            description: The device is not authenticated.
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Error'

          500:
            description: Internal error.
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Error'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  
  responses:
    UnauthorizedError:
      description: Access token in missing or invalid
  schemas:      
    Error:
      description: Error descriptor.
      type: object
      properties:
        error:
          description: Description of the error.
          type: string
        request_id:
          description: Request ID (same as in X-MEN-RequestID header).
          type: string
      example:
        error: "Error string"
        request_id: "f7881e82-0492-49fb-b459-795654e7188a"

    AI_PACKAGE:
      description: AI engine/model model
      type: object
      properties:
        type:
          description: Type of config engine or model.
          type: string
        name:
          description: Name of the package.
          type: string
        version:
          description: Package version.
          type: string
        status:
          description: Status of deployment (Created, Pending, In-progress, Finished)
          type: string

    Lconf:
      description: local configurations model
      type: object
      properties:
        config_details:
          description: JSON string with configurations details
          type: string
        device_id:
          description: device id for which local configuration is created
          type: string
        id:
          description: db assigned id
          type: string
        ai_package:
          type: array
          items:
            $ref: '#/components/schemas/AI_PACKAGE'
        created_ts:
          type: string
          format: datetime
          description: Created timestamp
        updated_ts:
          type: string
          format: datetime
          description: Updated timestamp
      example:
       config_details: "{ \"protection_type\" : \"LinkProt\", \"key_rotation_period\" : \"15\", \"key_predelivery_win\" : \"1\", \"cam_net_if\" : \"eth0\", \"cam_onvif_port\" : \"92\", \"cam_rtsp_port\" : \"990\", \"cam_addr\" : \"9900\", \"cam_port\" : \"121\" }"
       created_ts: "2019-04-16T06:44:16.386Z"
       device_id: "5ca5a5e53654df850001145049"
       id: "5cb579c066b19200019d546f"
       ai_package: [{"type": "engine","name": "abc","version": "0.5.8","status": "installed"},{"type": "model","name": "abc1","version": "0.5.9","status": "installed"}]
       updated_ts: "2019-04-16T06:44:16.386Z"

    LocalConf:
      description: local configurations model
      type: object
      properties:
        id:
          description: db assigned id
          type: string
        device_id:
          description: device id for which local configuration is created
          type: string
        uuid:
          type: string
        config_details:
          description: JSON string with configurations details
          type: string
        ai_package:
          type: array
          items:
            $ref: '#/components/schemas/AI_PACKAGE'
        created_ts:
          type: string
          format: datetime
          description: Created timestamp
        updated_ts:
          type: string
          format: datetime
          description: Updated timestamp
