openapi: 3.0.0
info:
  version: '1.0.0'
  title: 'Local Confiugurations API'
  description: 'API for managing  local configurations. For device to store a bulk of data inside server database. Device is responsible of creating/updating/deleting content of data. Data is unique by device'
  contact:
    name: Prabhu Chawandi
    url: smardtv.com
    email: prabhu.chawandi@smartdtv.com
    
servers: 
  - url: https://smarthing-cloud-dev.com
    description: Dev Server
   
  - url: https://smarthing-cloud.com
    description: Prod Server

paths: 
  /api/devices/v1/localconf/lconf_requests/{deviceId}:
    patch: 
        summary: Add the local configuration details for VSAAS flavor
        parameters:
         - name : deviceId
           required: true
           in: path
           description: Device Id for which local configuration is added
           schema:
             type: string
        
        requestBody:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Lconf'

        responses:
          200:
            description: Successfull addition of the local configuration
          
          400:
            description: Missing/malformed request parameters or body. See error for details.
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Error'

          401:
            description: The device is not authenticated.
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Error'

          500:
            description: Internal error.
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Error'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  
  responses:
    UnauthorizedError:
      description: Access token in missing or invalid
  schemas:      
    Error:
      description: Error descriptor.
      type: object
      properties:
        error:
          description: Description of the error.
          type: string
        request_id:
          description: Request ID (same as in X-MEN-RequestID header).
          type: string
      example:
        error: "failed to decode device group data: JSON payload is empty"
        request_id: "f7881e82-0492-49fb-b459-795654e7188a"

    Lconf:
      description: local configurations model
      type: object
      properties:
        config_details:
          description: JSON string with configurations details
          type: string
        device_id:
          description: device id for which local configuration is created
          type: string
        id:
          description: db assigned id
          type: string
        created_ts:
          type: string
          format: datetime
          description: Created timestamp
        updated_ts:
          type: string
          format: datetime
          description: Updated timestamp
      example:
       config_details: "{ \"protection_type\" : \"LinkProt\", \"key_rotation_period\" : \"15\", \"key_predelivery_win\" : \"1\", \"cam_net_if\" : \"eth0\", \"cam_onvif_port\" : \"92\", \"cam_rtsp_port\" : \"990\", \"cam_addr\" : \"9900\", \"cam_port\" : \"121\" }"
       created_ts: "2019-04-16T06:44:16.386Z"
       device_id: "5ca5a5e53654df850001145049"
       id: "5cb579c066b19200019d546f"
       updated_ts: "2019-04-16T06:44:16.386Z"
   
